apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

images:
  - name: ghcr.io/brian-e-ramirez-zea/portfolio-webapp
    newTag: sha-7b3f91a # {"$imagepolicy": "flux-system:portfolio-webapp:tag"}
